import unittest

import day7
import utils

PART_1_EXAMPLE = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


class Part1Tests(unittest.TestCase):

    def test_example(self):
        self.assertEqual(21, day7.part_1_answer(utils.to_lines(PART_1_EXAMPLE)))

    def test_with_input(self):
        self.assertEqual(1630, day7.part_1_answer(utils.read_input_lines(7)))


class Part2Tests(unittest.TestCase):

    def test_example(self):
        self.assertEqual(40, day7.part_2_answer(utils.to_lines(PART_1_EXAMPLE)))

    def test_with_input(self):
        self.assertEqual(47857642990160, day7.part_2_answer(utils.read_input_lines(7)))
